export type LaunchReadinessStep = {
  name: string;
  script: string;
};

export const launchReadinessSteps: LaunchReadinessStep[] = [
  { name: "preflight fixtures", script: "test:preflight" },
  { name: "migration files", script: "test:migrations" },
  { name: "health endpoint", script: "test:healthz" },
  { name: "docker health", script: "test:docker-health" },
  { name: "admin health API", script: "test:admin-health" },
  { name: "admin health UI", script: "test:admin-health-ui" },
  { name: "billing policy", script: "test:billing" },
  { name: "billing sync", script: "test:billing-sync" },
  { name: "billing route", script: "test:billing-route" },
  { name: "stripe webhook fixtures", script: "test:stripe-webhook" },
  { name: "stripe webhook route", script: "test:stripe-route" },
  { name: "security rate limits", script: "test:security-rate-limit" },
  { name: "analysis rate limits", script: "test:analysis-rate-limit" },
  { name: "security headers", script: "test:security-headers" },
  { name: "CSP reports", script: "test:csp-report" },
  { name: "operation logs", script: "test:operation-log" },
  { name: "operation routes", script: "test:operation-routes" },
  { name: "public URL safety", script: "test:public-url" },
  { name: "analysis route", script: "test:analysis-route" },
  { name: "online SEO and GEO scoring", script: "test:online-score" },
  { name: "public access policy", script: "test:access-policy" },
  { name: "password-protected pilot AI policy", script: "test:pilot-ai-policy" },
  { name: "site types through API and Chromium", script: "test:site-api-matrix" },
  { name: "analysis job route", script: "test:analysis-job-route" },
  { name: "audit route", script: "test:audit-route" },
  { name: "audit authorization", script: "test:audit-authorization" },
  { name: "analysis worker", script: "test:worker" },
  { name: "worker operations", script: "test:worker-operations" },
  { name: "backup runbook", script: "test:backup-runbook" },
  { name: "backup behavior", script: "test:backup-behavior" },
  { name: "seed guard", script: "test:seed-guard" },
  { name: "AI Visibility", script: "test:ai-visibility" },
  { name: "GEO positioning", script: "test:geo-positioning" },
  { name: "GEO publication gate", script: "test:geo-publication-gate" },
  { name: "deployment docs", script: "test:deployment-docs" },
  { name: "measurement calibration", script: "test:measurement-calibration" },
  { name: "rendered measurements", script: "test:rendered" },
  { name: "production build", script: "build" },
  { name: "runtime security headers", script: "test:runtime-security-headers" },
  { name: "admin health browser flow", script: "test:admin-health-flow" },
  { name: "cloud role browser flow", script: "test:cloud-role-flow" },
  { name: "browser app flow", script: "test:app-flow" },
  { name: "browser smoke", script: "test:smoke" },
];
