import assert from 'node:assert/strict';
import { reviewActions } from '../lib/review-actions';
import { evidenceReviewReason } from '../lib/evidence-review';
import type { MeasurementEvidence } from '../lib/measurement-contract';
const base: MeasurementEvidence={source:'crawler',confidence:'low',scoreEligible:false,contractVersion:'0.7.0'};
assert.deepEqual(reviewActions(),[]);
assert.deepEqual(reviewActions({t64:{...base,reasonCode:'method-not-calibrated'},geo:{...base,source:'ai-engine'}}),[],'unknown method or AI source alone is not an actionable site defect');
const multi={...base,pageResults:[{url:'https://example.com/a',status:'Pass' as const,declarations:['A','B']}]};
assert.equal(evidenceReviewReason(multi),'reviewMetadata');
const result=reviewActions({o5:multi,o8:multi,u33:{...base,pageResults:[{url:'https://example.com/b',status:'N/A',measurementState:'incomplete-resources'}]},u37:{...base,pageResults:[{url:'https://example.com/c',status:'N/A',measurementState:'incomplete-resources'}]}});
assert.equal(result.length,3,'different resource URLs in later controls must remain discoverable');
assert.equal(result[0].id,'o5'); assert.equal(result[0].kind,'descriptions');
assert.deepEqual(result[1].urls,['https://example.com/b'],'a button must only promise URLs available in its target evidence');
console.log('Review actions: evidence-only follow-ups, no invented AI or timing problems, deduplication and matching destinations passed.');
assert.deepEqual(reviewActions({t1:{...base,scope:{tested:1,discovered:10,complete:false},pageResults:[{url:'https://example.com/',status:'N/A'}]}}),[],'aggregate incomplete scope must not invent which page lacks measurements');
const coverage=reviewActions({u33:{...base,pageResults:[{url:'https://example.com/a',status:'N/A',measurementState:'incomplete-coverage'},{url:'https://example.com/a',status:'N/A',measurementState:'incomplete-coverage'},{url:'https://example.com/b',status:'Pass',measurementState:'complete'}]},u37:{...base,pageResults:[{url:'https://example.com/c',status:'N/A',measurementState:'incomplete-coverage'}]}});
assert.deepEqual(coverage,[{id:'u33',kind:'coverage',urls:['https://example.com/a']},{id:'u37',kind:'coverage',urls:['https://example.com/c']}],'each coverage action only lists explicit incomplete pages in its own target evidence');
assert.deepEqual(result[2],{id:'u37',kind:'resources',urls:['https://example.com/c']});
const overlapping=reviewActions({u33:{...base,pageResults:[{url:'https://example.com/a',status:'N/A',measurementState:'incomplete-resources'}]},u37:{...base,pageResults:[{url:'https://example.com/a',status:'N/A',measurementState:'incomplete-resources'},{url:'https://example.com/b',status:'N/A',measurementState:'incomplete-resources'}]},u39:{...base,pageResults:[{url:'https://example.com/b',status:'N/A',measurementState:'incomplete-resources'}]}});
assert.deepEqual(overlapping,[{id:'u33',kind:'resources',urls:['https://example.com/a']},{id:'u37',kind:'resources',urls:['https://example.com/b']}],'same-kind URLs are deduplicated across controls without hiding new URLs');
